from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

module fermi_lat_data_workflow:
    snakefile:
        # here, plain paths, URLs and the special markers for code hosting providers (see below) are possible.
        github("adonath/snakemake-workflow-fermi-lat", path="workflow/Snakefile", branch="main")
    config: config["fermi-lat-data"]

use rule * from fermi_lat_data_workflow as fermi_lat_data_*