name: jolideco-fermi-examples

channels:
  - conda-forge
  - bioconda 
  - fermi

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - snakemake>=6.4.1
  - gammapy>=1.0
  - notebook>=6.5.2
  - fermitools>=2.2.0