# Conda environment for reducing fermi data
name: snakemake-workflow-template

channels:
  - conda-forge

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.10
  - snakemake>=6.4.1
  - pydantic>=1.9.0
